# Generated by Django 5.1.7 on 2025-04-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judgy", "0002_alter_submission_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="language",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="submission",
            name="output",
            field=models.TextField(blank=True, null=True),
        ),
    ]
