# Generated by Django 5.1.7 on 2025-04-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judgy", "0003_submission_language_submission_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="file_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
