# Generated by Django 5.1.7 on 2025-04-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("judgy", "0005_useruniquetoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useruniquetoken",
            old_name="datetime",
            new_name="creation_time",
        ),
    ]
