# Generated by Django 5.1.7 on 2025-04-24 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("judgy", "0006_rename_datetime_useruniquetoken_creation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useruniquetoken",
            name="creation_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
