# Generated by Django 5.1.2 on 2025-10-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgy', '0007_alter_useruniquetoken_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='subjective',
            field=models.BooleanField(default=False),
        ),
    ]
