# Generated by Django 5.1.2 on 2025-10-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgy', '0008_problem_subjective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
