from django.urls import path
from .views import (
    home_view,
    login_view,
    logout_view,
    register_view,
    verify_view,
    notifications_view,
    notification_clear_view,
    set_timezone_view,
    competition_create_view,
    competition_code_view,
    problems_update_view,
    team_enroll_view,
    team_join_accept_view,
    team_join_decline_view,
    team_leave_view,
    team_invite_view,
    team_invite_accept_view,
    team_invite_decline_view,
    team_name_view,
    competitions_view,
    download_view,
    submit_view,
    output_view,
    rankings_view,
    get_members_view,
    CompUpdate,
    ProblemUpdate
)

app_name = 'judgy'

urlpatterns = [
    path('', home_view, name='home'),
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
    path('register', register_view, name='register'),
    path('verify', verify_view, name='verify'),
    path('notifications', notifications_view, name='notifications'),
    path('notification/<str:id>/clear', notification_clear_view, name='notification_clear'),
    path('set-timezone', set_timezone_view, name='set_timezone'),
    path('competition/create', competition_create_view, name='competition_create'),
    path('competition/<str:code>/problems/update', problems_update_view, name='problems_update'),
    path('competition/<str:code>', competition_code_view, name='competition_code'),
    path('competition/<str:code>/team/enroll', team_enroll_view, name='team_enroll'),
    path('team/join/<str:id>/accept', team_join_accept_view, name='team_join_accept'),
    path('team/join/<str:id>/decline', team_join_decline_view, name='team_join_decline'),
    path('competition/<str:code>/team/leave', team_leave_view, name='team_leave'),
    path('competition/<str:code>/team/invite', team_invite_view, name='team_invite'),
    path('team/invite/<str:id>/accept', team_invite_accept_view, name='team_invite_accept'),
    path('team/invite/<str:id>/decline', team_invite_decline_view, name='team_invite_decline'),
    path('competition/<str:code>/team/<str:name>', team_name_view, name='team_name'),
    path('competitions', competitions_view, name='competitions'),
    path('competition/<str:code>/<str:problem_name>/download', download_view, name='download'),
    path('competition/<str:code>/<str:problem_name>/submit', submit_view, name='submit'),
    path('competition/<str:code>/rankings', rankings_view, name='rankings'),
    path('competition/<str:code>/<str:problem_name>/submission/output', output_view, name='output'),
    path('competition/<str:code>/team/<str:name>/members', get_members_view, name='team_members'),
    path('competition/<str:code>/update', CompUpdate.as_view(), name="update_competition"),
    path('competiiton/<str:code>/<str:problem_name>/update', ProblemUpdate.as_view(), name="update_problem")
]
