services:
  db:
    image: mysql/mysql-server:8.0
    container_name: judgy_mysql_prod
    restart: always
    volumes:
      - prod_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - prod

  django_gunicorn:
    container_name: judgy_app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/app/staticfiles
      - ./competitions:/app/competitions
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - prod

  nginx:
    container_name: judgy_nginx
    build: ./nginx
    env_file:
      - .env
    volumes:
      - static:/app/staticfiles
      - ./nginx/default.conf:/etc/nginx/templates/default.template.conf
      - acme-challenge:/app/acme-challenges
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_gunicorn
    networks:
      - prod
    entrypoint: [ "/bin/bash", "/entrypoint.sh" ]

networks:
  prod:
    driver: bridge

volumes:
  static:
  prod_data:
  acme-challenge: 
