services:
  db:
    image: mysql:latest
    container_name: judgy_mysql
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p", "${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: python:latest
        COMP_CODE: ${COMP_CODE}
    image: judgy-${COMP_CODE}-python_app

  ruby_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ruby:latest
        COMP_CODE: ${COMP_CODE}

  gcc_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: gcc:latest
        COMP_CODE: ${COMP_CODE}

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: node:latest
        COMP_CODE: ${COMP_CODE}
        
volumes:
  data:
