services:
  db:
    image: mysql/mysql-server:8.0
    container_name: judgy_mysql_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - prod_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - prod

  # django_gunicorn:
  #   container_name: judgy_app
  #   build:
  #     context: .
  #   restart: always
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   env_file:
  #     - .env
  #   volumes:
  #     - static:/app/staticfiles
  #     - ./competitions:/app/competitions
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - prod

  nginx:
    container_name: judgy_nginx
    build: ./nginx
    restart: always
    depends_on:
      - django_gunicorn
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    env_file:
      - .env
    volumes:
      - ./django-project/staticfiles:/app/staticfiles
      - ./nginx/default.conf:/etc/nginx/templates/default.template.conf
      - acme-challenge:/app/acme-challenges
    ports:
      - "80:80"
      - "443:443"
    networks:
      - prod

networks:
  prod:
    driver: bridge

volumes:
  static:
  prod_data:
  acme-challenge:
